### ISSUE TITLE
Add matching pattern for SWRL rules

### ISSUE THREAD

**Issue by cmungall** [balhoff/owl-to-rules#2]
Or are these automatically translated by Jena anyway?

Not urgent, just a matter of completion/interest.

**Comment by balhoff** [comment]
Good idea! Not automatic, but there may be an existing translator that could be incorporated; will need to research.

**Comment by balhoff** [comment]
Not fully implemented but 'object' parts are done now. #4 will include data property reasoning for SWRL.
